CREATE SCHEMA o.s2;
CREATE TABLE o.s2.w AS SELECT i, i * 2 AS j, 'w' || i AS k FROM range(3000) r(i);
DELETE FROM o.main.child WHERE id % 11 = 0;
CREATE TABLE o.main.child_copy AS SELECT * FROM o.main.child;
DROP TABLE o.main.child;
INSERT INTO o.main.t (id, name, score, dt) VALUES (100000, 'late', 3.25, DATE '2030-01-01');
UPDATE o.main.t SET score = score + 1, tags = ['u'] WHERE id % 97 = 0;
DELETE FROM o.s.other WHERE x % 5 = 0;
UPDATE o.s.other SET y = 'upd' WHERE x % 13 = 0;
ALTER TABLE o.s.other RENAME TO other2;
ALTER TABLE o.s.other2 ADD COLUMN z INTEGER DEFAULT 7;
ALTER TABLE o.s.other2 RENAME COLUMN y TO yy;
ALTER TABLE o.s.other2 ALTER COLUMN x TYPE VARCHAR;
ALTER TABLE o.s.other2 ALTER COLUMN z SET DEFAULT 9;
INSERT INTO o.s.other2 (x, yy) VALUES ('new', 'row');
ALTER TABLE o.s2.w DROP COLUMN j;
ALTER TABLE o.s2.w ADD PRIMARY KEY (i);
CREATE INDEX w_k_idx ON o.s2.w (k);
ALTER VIEW o.main.v RENAME TO v2;
CREATE VIEW o.s2.wv AS SELECT i, k FROM o.s2.w WHERE i < 10;
CREATE MACRO o.s2.twice(x) AS x * 2;
CREATE TYPE o.main.color AS ENUM ('red', 'green');
CREATE TABLE o.s2.colors (c o.main.color, n INTEGER);
INSERT INTO o.s2.colors VALUES ('red', 1), ('green', 2), (NULL, 3);
SELECT nextval('o.main.seq') FROM range(5);
CREATE SEQUENCE o.s2.seq2 START 100 INCREMENT 3;
SELECT nextval('o.s2.seq2');
COMMENT ON TABLE o.s2.w IS 'wal table';
COMMENT ON COLUMN o.s2.w.k IS 'k column';
CREATE TABLE o.s2.nn (a INTEGER NOT NULL, b INTEGER);
INSERT INTO o.s2.nn VALUES (1, 2);
ALTER TABLE o.s2.nn ALTER COLUMN a DROP NOT NULL;
ALTER TABLE o.s2.nn ALTER COLUMN b SET NOT NULL;
DROP MACRO o.main.add1;
CREATE TABLE o.main.dropme (a INTEGER);
DROP TABLE o.main.dropme;
CREATE SCHEMA o.gone;
CREATE TABLE o.gone.x (a INTEGER);
DROP SCHEMA o.gone CASCADE;
