FROM public.ecr.aws/docker/library/node:22
WORKDIR /test-app

COPY . .

RUN npm ci --include=dev --legacy-peer-deps

RUN npm run build

RUN npx playwright install --with-deps

EXPOSE 3000
CMD ["npm", "run", "dev:backend"]
