////////////////////////////////////////////////////////////////////////////////
/// DISCLAIMER
///
/// Copyright 2026 SereneDB GmbH, Berlin, Germany
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///
///     http://www.apache.org/licenses/LICENSE-2.0
///
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
///
/// Copyright holder is SereneDB GmbH, Berlin, Germany
////////////////////////////////////////////////////////////////////////////////

#pragma once

#include <memory>
#include <string>
#include <vector>

#include "iresearch/search/filter.hpp"
#include "iresearch/utils/string.hpp"

namespace irs {
namespace analysis {

class ShingleAnalyzer;
struct TokenizerConfig;

}  // namespace analysis

class ByPhraseNgram;

// Position-free phrase filter over a ShingleAnalyzer-indexed field. Candidate
// documents are generated by ANDing the query phrase's shingle terms (a
// necessary-but-not-sufficient condition), then -- unless the match is exact
// by construction -- each candidate is verified by re-checking that the query
// tokens appear as an ordered contiguous run in the document's stored token
// stream (read from the columnstore via `store_field_id`).
//
//   * phrase of 1 token            -> a single unigram term, no verification
//   * phrase of <= max_shingle_size -> a single shingle term, no verification
//     (the shingle already encodes the ordered adjacency of its tokens)
//   * longer phrase                -> AND of overlapping max-size shingles,
//                                     then per-candidate verification
struct ByPhraseNgramOptions {
  using FilterType = ByPhraseNgram;

  // Strategy A (position-free) candidate-generation terms (ANDed, deduped):
  // one term (the exact case) or the phrase's overlapping shingles. With a
  // frequent-words bound, tokens not implied by an indexed shingle contribute
  // their unigrams instead.
  std::vector<bstring> shingles;
  // Strategy B (positional) plan: a greedy cover of the phrase by the largest
  // indexed shingle at each step; a tail shorter than min_shingle_size is
  // covered by an overlapping shingle ending at the phrase end, with a
  // unigram fallback only when no such shingle is indexed.
  // `positional_starts[i]` is the token index where `positional_terms[i]`
  // begins; Prepare turns start gaps into ByPhrase position offsets, so the
  // phrase stays exact (the gap also enforces the seam between terms).
  std::vector<bstring> positional_terms;
  std::vector<uint32_t> positional_starts;
  // Ordered original query tokens, used to verify exact contiguity. A token
  // equal to `filler` marks a removed stopword and matches any single
  // document token during verification.
  std::vector<bstring> query_tokens;
  bstring filler;
  // The single shingle/unigram term in `shingles` is itself the exact answer;
  // no per-candidate verification is needed.
  bool exact{false};
  // The indexed field carries positions (Strategy B): answer via a positional
  // phrase over the shingle cover (`positional_terms`/`positional_starts`),
  // exact by construction with no verification. Set by the filter builder from
  // the column's index features so the choice is segment-independent (catalog
  // features are uniform across segments), which the per-segment prepare model
  // requires. When false, the position-free verify path (Strategy A) is used.
  bool positional{false};
  // Columnstore field id the verifier reads on the position-free path:
  // either the packed token stream (raw_store == false) or the raw column
  // value (raw_store == true), which is re-tokenized per candidate with an
  // analyzer built from `verify_config`. Unused when the field has positions:
  // `Prepare` detects that and answers via a positional phrase with no
  // verification.
  field_id store_field_id{0};
  bool raw_store{false};
  std::shared_ptr<const analysis::TokenizerConfig> verify_config;

  bool operator==(const ByPhraseNgramOptions& rhs) const = default;

  ByPhraseNgramOptions() = default;
  ByPhraseNgramOptions(const ByPhraseNgramOptions&) = default;
  ByPhraseNgramOptions(ByPhraseNgramOptions&&) noexcept = default;
  ByPhraseNgramOptions& operator=(const ByPhraseNgramOptions&) = default;
  ByPhraseNgramOptions& operator=(ByPhraseNgramOptions&&) noexcept = default;

  // Decompose `phrase` into candidate shingles + ordered verification tokens by
  // driving `analyzer` -- the same code path that indexed the documents.
  ByPhraseNgramOptions(std::string_view phrase,
                       analysis::ShingleAnalyzer& analyzer);
};

class ByPhraseNgram final : public FilterWithField<ByPhraseNgramOptions> {
 public:
  QueryBuilder::ptr PrepareSegment(const SubReader& segment,
                                   const PrepareContext& ctx) const final;

  PrepareCollector::ptr MakeCollector(const Scorer* scorer) const final;
};

}  // namespace irs
