////////////////////////////////////////////////////////////////////////////////
/// DISCLAIMER
///
/// Copyright 2026 SereneDB GmbH, Berlin, Germany
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///
///     http://www.apache.org/licenses/LICENSE-2.0
///
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
///
/// Copyright holder is SereneDB GmbH, Berlin, Germany
////////////////////////////////////////////////////////////////////////////////

#pragma once

#include <string>
#include <vector>

#include "iresearch/search/filter.hpp"
#include "iresearch/utils/string.hpp"

namespace irs {
namespace analysis {

class ShingleAnalyzer;

}  // namespace analysis

class ByPhraseNgram;

// Position-free phrase filter over a ShingleAnalyzer-indexed field. Candidate
// documents are generated by ANDing the query phrase's shingle terms (a
// necessary-but-not-sufficient condition), then -- unless the match is exact
// by construction -- each candidate is verified by re-checking that the query
// tokens appear as an ordered contiguous run in the document's stored token
// stream (read from the columnstore via `store_field_id`).
//
//   * phrase of 1 token            -> a single unigram term, no verification
//   * phrase of <= max_shingle_size -> a single shingle term, no verification
//     (the shingle already encodes the ordered adjacency of its tokens)
//   * longer phrase                -> AND of overlapping max-size shingles,
//                                     then per-candidate verification
struct ByPhraseNgramOptions {
  using FilterType = ByPhraseNgram;

  // Strategy A (position-free) candidate-generation terms (ANDed): one term
  // (the exact case) or the phrase's overlapping shingles / unigrams. With a
  // frequent-words bound, unindexed shingles are replaced by their unigrams.
  std::vector<bstring> shingles;
  // Strategy B (positional) plan: a greedy non-overlapping cover of the phrase
  // by the largest indexed shingle at each step, falling back to a unigram.
  // `positional_starts[i]` is the token index where `positional_terms[i]`
  // begins; Prepare turns start gaps into ByPhrase position offsets, so the
  // phrase stays exact (the gap also enforces the seam between terms).
  std::vector<bstring> positional_terms;
  std::vector<uint32_t> positional_starts;
  // Ordered original query tokens, used to verify exact contiguity.
  std::vector<bstring> query_tokens;
  // The single shingle/unigram term in `shingles` is itself the exact answer;
  // no per-candidate verification is needed.
  bool exact{false};
  // Columnstore field id of the packed token stream, read by the verifier on
  // the position-free (Strategy A) path. Unused when the field has positions:
  // `Prepare` detects that and answers via a positional phrase (Strategy B)
  // with no verification.
  field_id store_field_id{0};

  bool operator==(const ByPhraseNgramOptions& rhs) const = default;

  ByPhraseNgramOptions() = default;
  ByPhraseNgramOptions(const ByPhraseNgramOptions&) = default;
  ByPhraseNgramOptions(ByPhraseNgramOptions&&) noexcept = default;
  ByPhraseNgramOptions& operator=(const ByPhraseNgramOptions&) = default;
  ByPhraseNgramOptions& operator=(ByPhraseNgramOptions&&) noexcept = default;

  // Decompose `phrase` into candidate shingles + ordered verification tokens by
  // driving `analyzer` -- the same code path that indexed the documents.
  ByPhraseNgramOptions(std::string_view phrase,
                       analysis::ShingleAnalyzer& analyzer);
};

class ByPhraseNgram final : public FilterWithField<ByPhraseNgramOptions> {
 public:
  static Query::ptr Prepare(const PrepareContext& ctx, std::string_view field,
                            const ByPhraseNgramOptions& options);

  Query::ptr prepare(const PrepareContext& ctx) const final {
    return Prepare(ctx.Boost(Boost()), field(), options());
  }
};

}  // namespace irs
