////////////////////////////////////////////////////////////////////////////////
/// DISCLAIMER
///
/// Copyright 2026 SereneDB GmbH, Berlin, Germany
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///
///     http://www.apache.org/licenses/LICENSE-2.0
///
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
///
/// Copyright holder is SereneDB GmbH, Berlin, Germany
////////////////////////////////////////////////////////////////////////////////

#pragma once

#include <duckdb/main/database.hpp>

#include <string>

namespace sdb::connector {

// Elasticsearch-compatible operations as table functions; the HTTP handlers
// are thin glue around CALL es_*(...). An ES index is a table in the "es"
// schema: "_id" VARCHAR primary key, one typed column per mapped property,
// "_source" VARCHAR with the original document; "text" properties get an
// inverted index, which is also what distinguishes them from "keyword" when
// the mapping is read back.
//
//   es_create_index(name, mappings_json) -> (acknowledged BOOLEAN)
//   es_drop_index(name)                  -> (acknowledged BOOLEAN)
//   es_mapping(name)                     -> (mappings VARCHAR)
//   es_cat_indices()                     -> (index VARCHAR, docs_count BIGINT)
//
// Write path: es_doc/es_bulk emit rows shaped exactly like the target table,
// consumed as INSERT INTO "es"."<index>" SELECT * FROM es_*(...). es_bulk
// also appends per-item response JSON to the ConnectionContext response sink
// when one is set (there is no INSERT ... RETURNING on serenedb tables).
//
//   es_doc(name, id, doc_json)           -> one table-shaped row
//   es_bulk(name, ndjson)                -> table-shaped rows
//   es_refresh(name)                     -> (acknowledged BOOLEAN); '' = all
void RegisterEsFunctions(duckdb::DatabaseInstance& db);

// 20-char base64url document id, like ES autogenerated ids.
std::string GenerateEsDocId();

// The inverted index on an ES index's text properties is the relation
// "<index>$text" ('$' cannot appear in a validated index name); _search
// queries with match clauses run against it.
inline constexpr std::string_view kEsTextIndexSuffix = "$text";

}  // namespace sdb::connector
