#!/bin/sh
set -e

action="$1"
old_version="$2"

SERENEDB="/usr/sbin/serened"

# source debconf library
. /usr/share/debconf/confmodule
. /usr/share/serenedb/serenedb-helper

if test -d /var/lib/serenedb -a ! -f /usr/sbin/serened; then
    NEW_INSTALL_EXISTING_DIR=true
else
    NEW_INSTALL_EXISTING_DIR=false
fi

if [ -d "/run/systemd/system" ] ; then
    if deb-systemd-invoke is-active serenedb.service 2>&1 >/dev/null ; then
        deb-systemd-invoke stop serenedb.service >/dev/null \
            || ar_err "failed to stop serenedb service" $?
    fi
else
    if [ -x "/etc/init.d/serenedb" ]; then
        invoke-rc.d serenedb stop \
            || ar_err "failed to stop serenedb service" $?
    fi
fi

if test "$action" = "configure" -a \
        -z "$2" -a \
        "$NEW_INSTALL_EXISTING_DIR" = "false" ; then

    db_get @EDITION@/password

    # Escape backslashes and quotes
    if [ -n "$RET" ]; then
        SERENEDB_DEFAULT_ROOT_PASSWORD="$(echo "$RET" | sed -e 's;\\\\;\\\\\\\\;g' -e 's;";\\\\";g')" \
            /usr/sbin/serene-init-database \
                --server.rest-server false \
                --server.statistics false \
                --uid serenedb --gid serenedb || true
    fi

    db_set @EDITION@/password_again ""
    db_set @EDITION@/password ""
    db_go
fi

# check if we should upgrade the database directory
UPGRADE=false #requires upgrade
set +e
$SERENEDB --uid serenedb --gid serenedb \
          --server.rest-server false --log.foreground-tty false \
          --database.check-version
exit_status=$?
set -e

if [ $exit_status -eq "$(ar_exitcode_string_to_num EXIT_UPGRADE_REQUIRED)" ]; then
    UPGRADE=true
else
    ar_exit_by_num $exit_status
fi


db_get @EDITION@/upgrade #wants upgrade
if [ "$RET" = "true" ];  then
    if [ "$UPGRADE" = "true" ];  then
        db_get @EDITION@/backup

        if [ "$RET" = "true" ];  then
            BACKUP="/var/lib/serenedb-$(date +%F-%H-%M-%S)"
            cp -a /var/lib/serenedb "$BACKUP"
            echo "A backup of your database files has been stored in $BACKUP."
        fi

        echo "Upgrading database files."
        set +e
        $SERENEDB --uid serenedb --gid serenedb --server.rest-server false --log.level error --database.auto-upgrade || ar_ferr $?
        set -e
    else
        echo "Database files are up-to-date."
    fi
elif [ "$UPGRADE" = "true" ];  then
    echo "Warning: database files need upgrade, automatic upgrade is disabled, please do it manually."
    echo "After you've prepared your system for upgrade, please run "
    echo "  /usr/share/serenedb/serenedb-update-db"
    echo "  dpkg --pending --configure"
    echo "after the packaging system is in stable state again."
else
    echo "Database files are up-to-date."
fi

db_stop

if [ -d /run/systemd/system ] ; then
    deb-systemd-helper unmask serenedb.service >/dev/null || true

    if deb-systemd-helper --quiet was-enabled serenedb.service; then
        # Enables the unit on first installation, creates new
        # symlinks on upgrades if the unit file has changed.
        deb-systemd-helper enable serenedb.service >/dev/null || true
    else
        # Update the statefile to add new symlinks (if any), which need to be
        # cleaned up on purge. Also remove old symlinks.
        deb-systemd-helper update-state serenedb.service >/dev/null || true
    fi

    if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null || true
        deb-systemd-invoke start serenedb.service >/dev/null || true
    fi
else
    if [ -x "/etc/init.d/serenedb" ]; then
        update-rc.d serenedb defaults >/dev/null
        invoke-rc.d serenedb start || exit $?
    fi
fi
exit 0
