#!/bin/sh
set -e

if [ "$1" = "purge" ] ; then
  update-rc.d serenedb remove >/dev/null
fi

# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
  systemctl --system daemon-reload >/dev/null || true
fi

if [ "$1" = "remove" ]; then
  if [ -x "/usr/bin/deb-systemd-helper" ]; then
    deb-systemd-helper mask serenedb.service >/dev/null
  fi
fi

if [ "$1" = "purge" ]; then
  if [ -x "/usr/bin/deb-systemd-helper" ]; then
    deb-systemd-helper purge serenedb.service >/dev/null
    deb-systemd-helper unmask serenedb.service >/dev/null
  fi
fi

if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
  . /usr/share/debconf/confmodule
  db_purge
fi

if [ purge = "$1" ]; then
  rm -rf /var/log/serenedb
  rm -rf /var/lib/serenedb
  rm -rf /var/run/serenedb
fi
