#!/usr/bin/env bash
# Format third_party/duckdb*/ C/C++ files with clang-format 11.0.1 (the version
# duckdb's own scripts/format.py enforces) inside a docker container, so no
# local clang-format-11 install is required.
#
# Covered submodules: duckdb, duckdb_avro, duckdb_azure, duckdb_httpfs,
# duckdb_iceberg, duckdb_inet, duckdb_markdown, duckdb_postgres, duckdb_spatial,
# database-connector. Also covers duckdb_clickhouse, which is IN-TREE (part of
# this repo, not a submodule) -- its changed-file discovery and status use the
# main repo's git. Each directory is formatted with its own .clang-format.
#
# Usage:
#   scripts/format_duckdb.sh                # format files changed vs the
#                                             commit origin/main pins for
#                                             each submodule
#   scripts/format_duckdb.sh --base <ref>   # format files changed vs <ref>
#                                             (applied to every submodule)
#   scripts/format_duckdb.sh --files f1 f2  # format an explicit list (paths
#                                             relative to third_party/, e.g.
#                                             'duckdb/src/foo.cpp')
#   scripts/format_duckdb.sh --check        # report diffs only, do not write
#   scripts/format_duckdb.sh --staged       # scope to git-staged changes
#                                             (for the pre-commit hook)
#   scripts/format_duckdb.sh --all          # every tracked file, regardless
#                                             of any diff
#
# Scoping rules (the same as third_party/duckdb/scripts/format.py):
#   - only files under: src/ benchmark/ test/ tools/ examples/ extension/ scripts/
#     (third_party/, data/, etc. are skipped -- never reformat vendored code)
#   - skips files/dirs in duckdb's ignored_files / ignored_directories list
#   - skips files carrying "// This file is automatically generated by scripts/";
#     generated files without that marker are formatted, as format.py does
#   - only .cpp .hpp .h .c .cc .hh .ipp
#
# clang-format 11.0.1 lives in a venv under ~/.cache/serenedb-format, created on
# the first run and reused by every later one.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
THIRD_PARTY="$REPO_ROOT/third_party"
SUBMODULES=(duckdb duckdb_avro duckdb_azure duckdb_inet duckdb_markdown duckdb_httpfs duckdb_iceberg duckdb_postgres duckdb_spatial database-connector)
# In-tree directories (part of this repo, not submodules): their changed-file
# discovery and status run against the MAIN repo, scoped to their path.
INTREE=(duckdb_clickhouse)
ALL_DIRS=("${SUBMODULES[@]}" "${INTREE[@]}")
is_intree() {
	local d
	for d in "${INTREE[@]}"; do [[ "$d" == "$1" ]] && return 0; done
	return 1
}
# Track duckdb's own CI (CheckIssueForCodeFormatting.yml uses Python 3.12).
IMAGE="python:3.12-slim"

# An uninitialized submodule has no working tree, so it cannot have changed
# files to format -- skip it rather than failing. CI checks out with
# submodules: false, where every submodule is an empty directory.
present=()
for sm in "${SUBMODULES[@]}"; do
	sm_dir="$THIRD_PARTY/$sm"
	if [[ ! -d "$sm_dir/.git" && ! -f "$sm_dir/.git" ]]; then
		echo "note: skipping $sm (not a git checkout)" >&2
		continue
	fi
	present+=("$sm")
done
SUBMODULES=("${present[@]+"${present[@]}"}")
ALL_DIRS=("${SUBMODULES[@]+"${SUBMODULES[@]}"}" "${INTREE[@]}")
for sm in "${INTREE[@]}"; do
	if [[ ! -d "$THIRD_PARTY/$sm" ]]; then
		echo "error: $THIRD_PARTY/$sm does not exist" >&2
		exit 1
	fi
done

# Empty default means "the commit origin/main pins for each submodule", taken
# from the superproject's merge base: submodules are shallow clones whose
# origin/HEAD shares no history with the pinned commit.
BASE_REF=""
CHECK_ONLY=0
STAGED=0
ALL=0
EXPLICIT_FILES=()

while [[ $# -gt 0 ]]; do
	case "$1" in
	--base)
		BASE_REF="$2"
		shift 2
		;;
	--check)
		CHECK_ONLY=1
		shift
		;;
	--staged)
		STAGED=1
		shift
		;;
	--all)
		ALL=1
		shift
		;;
	--files)
		shift
		while [[ $# -gt 0 && "$1" != --* ]]; do
			EXPLICIT_FILES+=("$1")
			shift
		done
		;;
	-h | --help)
		sed -n '2,/^$/p' "$0"
		exit 0
		;;
	*)
		echo "unknown arg: $1" >&2
		exit 2
		;;
	esac
done

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT
FILES_TO_FORMAT="$TMP_DIR/files.txt"
INNER_SCRIPT="$TMP_DIR/run.sh"

# --- filters shared by every submodule -------------------------------------
ALLOWED_DIRS_RE='^(src|benchmark|test|tools|examples|extension|scripts)/'
EXT_RE='\.(cpp|hpp|h|c|cc|hh|ipp)$'

# duckdb's ignored_files (from scripts/format.py file_is_ignored: exact-basename
# match; the script there does `os.path.basename(p) in ignored_files`). So each
# entry must keep its specific extension -- 'types.hpp' is ignored, 'types.cpp'
# is not. The .test entry (test_insert_invalid.test) is omitted because EXT_RE
# already excludes test files.
IGNORED_FILES_RE='(^|/)(tpch_constants\.hpp|tpcds_constants\.hpp|test_csv_header\.hpp|duckdb\.cpp|duckdb\.hpp|json\.hpp|sqlite3\.h|shell\.c|termcolor\.hpp|httplib\.hpp|os_win\.c|glob\.c|printf\.c|helper\.hpp|single_thread_ptr\.hpp|types\.hpp|default_views\.cpp|default_functions\.cpp|release\.h|genrand\.cpp|address\.cpp|visualizer_constants\.hpp|icu-collate\.cpp|icu-collate\.hpp|yyjson\.cpp|yyjson\.hpp|duckdb_pdqsort\.hpp|pdqsort\.h|stubdata\.cpp|nf_calendar\.cpp|nf_calendar\.h|nf_localedata\.cpp|nf_localedata\.h|nf_zformat\.cpp|nf_zformat\.h|expr\.cc|function_list\.cpp|inlined_grammar\.hpp)$'

# duckdb's ignored_directories (mirrors scripts/format.py).
IGNORED_DIRS_RE='(/_generated/|^_generated/|tools/rpkg/src/duckdb/|tools/rpkg/inst/include/cpp11/|extension/external/|extension/tpcds/dsdgen/|extension/icu/third_party/|extension/icu/datetime/generated/|tools/nodejs/src/duckdb/|/\.eggs/|/__pycache__/|/dbgen/|/third_party/|^test/catch/)'

GENERATED_MARKER='// This file is automatically generated by scripts/'

UNFORMATTED_UPSTREAM_RE='^src/include/(duckdb_v2\.h|duckdb_extension_v2\.h|duckdb/main/capi_v2/extension_api_v2\.hpp)$'

# --- collect candidates per submodule, into one consolidated list ----------
# Output paths in $FILES_TO_FORMAT are relative to $THIRD_PARTY (e.g. duckdb/src/foo.cpp)
SUPER_BASE=""
if [[ -z "$BASE_REF" && ${#EXPLICIT_FILES[@]} -eq 0 && "$STAGED" -eq 0 && "$ALL" -eq 0 ]]; then
	SUPER_BASE="$(git -C "$REPO_ROOT" merge-base HEAD origin/main)"
fi
: >"$FILES_TO_FORMAT"
TOTAL=0
for sm in "${ALL_DIRS[@]}"; do
	sm_dir="$THIRD_PARTY/$sm"
	raw="$TMP_DIR/$sm.raw"
	cand="$TMP_DIR/$sm.cand"

	if [[ ${#EXPLICIT_FILES[@]} -gt 0 ]]; then
		: >"$raw"
		for f in "${EXPLICIT_FILES[@]}"; do
			if [[ "$f" == "$sm/"* ]]; then
				printf '%s\n' "${f#"$sm/"}" >>"$raw"
			fi
		done
	elif [[ "$ALL" -eq 1 ]]; then
		if is_intree "$sm"; then
			git -C "$REPO_ROOT" ls-files -- "third_party/$sm" | sed "s#^third_party/$sm/##" >"$raw"
		else
			git -C "$sm_dir" ls-files >"$raw"
		fi
	elif is_intree "$sm"; then
		# In-tree dir: discover via the MAIN repo, scoped to its path, then
		# strip the leading third_party/ so paths match the submodule form.
		if [[ "$STAGED" -eq 1 ]]; then
			git -C "$REPO_ROOT" diff --cached --name-only -- "third_party/$sm" | sed "s#^third_party/$sm/##" >"$raw"
		else
			intree_base="$(git -C "$REPO_ROOT" merge-base "${BASE_REF:-origin/HEAD}" HEAD)"
			{
				git -C "$REPO_ROOT" diff --name-only "$intree_base" -- "third_party/$sm"
				git -C "$REPO_ROOT" ls-files --others --exclude-standard -- "third_party/$sm"
			} | sed "s#^third_party/$sm/##" >"$raw"
		fi
	elif [[ "$STAGED" -eq 1 ]]; then
		git -C "$sm_dir" diff --cached --name-only >"$raw"
	elif [[ -n "$SUPER_BASE" ]]; then
		sm_base="$(git -C "$REPO_ROOT" ls-tree "$SUPER_BASE" "third_party/$sm" | awk '{print $3}')"
		if [[ -z "$sm_base" ]]; then
			echo "error: origin/main's merge base does not pin third_party/$sm; pass --base" >&2
			exit 1
		fi
		{
			git -C "$sm_dir" diff --name-only "$sm_base"
			git -C "$sm_dir" ls-files --others --exclude-standard
		} >"$raw"
	else
		{
			git -C "$sm_dir" diff --name-only "$(git -C "$sm_dir" merge-base "$BASE_REF" HEAD)"
			git -C "$sm_dir" ls-files --others --exclude-standard
		} >"$raw"
	fi

	grep -E "$EXT_RE" "$raw" 2>/dev/null |
		grep -E "$ALLOWED_DIRS_RE" |
		grep -vE "$IGNORED_FILES_RE" |
		grep -vE "$IGNORED_DIRS_RE" |
		grep -vE "$UNFORMATTED_UPSTREAM_RE" \
			>"$cand" || true

	kept="$TMP_DIR/$sm.kept"
	(cd "$sm_dir" && while IFS= read -r f; do [[ -f "$f" ]] && printf '%s\0' "$f"; done <"$cand" |
		xargs -0 -r grep -L -F -- "$GENERATED_MARKER") >"$kept" || true
	sed "s#^#$sm/#" "$kept" >>"$FILES_TO_FORMAT"
	sm_count=$(wc -l <"$kept" | tr -d ' ')
	echo "$sm: $sm_count file(s)"
	TOTAL=$((TOTAL + sm_count))
done

if [[ "$TOTAL" -eq 0 ]]; then
	echo "no files to format (base=${BASE_REF:-origin/main pins})"
	exit 0
fi
echo "total scope: $TOTAL file(s)"

# --- inner script that runs inside the container ---------------------------
# duckdb's format.py post-processes clang-format's output: it rewrites
# 'ARGS &&...args' back to 'ARGS &&... args' in .cpp/.hpp (clang-format 11
# disagrees with the tree's historical parameter-pack spacing), and its check
# mode ignores '...' lines altogether. Without the same fixup every run churns
# hundreds of untouched upstream lines. Check mode therefore compares against
# the post-processed output instead of using clang-format's --dry-run.
PACK_FIXUP='s/ARGS &&\.\.\.args/ARGS \&\&... args/g'

# Both modes render each file's formatted (and pack-fixed) output to a temp
# file and compare bytes: check mode reports differing files, write mode
# overwrites ONLY differing files. Never touching identical files keeps their
# mtime intact, so a formatting run over common headers doesn't trigger a
# rebuild of everything that includes them. The per-file work runs under
# xargs -P (batches amortize the shell spawn; clang-format dominates anyway).
cat >"$INNER_SCRIPT" <<INNER
#!/bin/sh
set -e
if [ ! -x /cache/venv/bin/clang-format ]; then
	python -m venv /cache/venv
	/cache/venv/bin/pip install --quiet --disable-pip-version-check clang_format==11.0.1
fi
export PATH="/cache/venv/bin:\$PATH"
cd /work
echo "clang-format: \$(clang-format --version)"
cat >/tmp/one.sh <<'ONE'
#!/bin/sh
tmp="/tmp/formatted.\$\$"
for f in "\$@"; do
	case "\$f" in
	*.cpp | *.hpp)
		clang-format --style=file --sort-includes=0 --assume-filename="\$f" <"\$f" | sed '$PACK_FIXUP' >"\$tmp"
		;;
	*)
		clang-format --style=file --sort-includes=0 --assume-filename="\$f" <"\$f" >"\$tmp"
		;;
	esac
	if ! cmp -s "\$tmp" "\$f"; then
		if [ -n "\$FMT_CHECK" ]; then
			echo "needs formatting: \$f"
			touch /tmp/fmt_failed
		else
			cat "\$tmp" >"\$f"
		fi
	fi
done
rm -f "\$tmp"
ONE
rm -f /tmp/fmt_failed
FMT_CHECK=""
[ "$CHECK_ONLY" -eq 1 ] && FMT_CHECK=1
export FMT_CHECK
xargs -a /tmp/files.txt -n 24 -P "\$(nproc)" sh /tmp/one.sh
[ ! -e /tmp/fmt_failed ]
INNER

# --- run --------------------------------------------------------------------
# Mount third_party/ as /work so paths like duckdb/src/foo.cpp resolve and
# clang-format finds each submodule's own .clang-format via parent lookup.
CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/serenedb-format"
mkdir -p "$CACHE_DIR"
docker run --rm \
	-u "$(id -u):$(id -g)" \
	-v "$THIRD_PARTY":/work \
	-v "$CACHE_DIR":/cache \
	-v "$FILES_TO_FORMAT":/tmp/files.txt:ro \
	-v "$INNER_SCRIPT":/tmp/run.sh:ro \
	-e HOME=/tmp \
	"$IMAGE" sh /tmp/run.sh

if [[ "$CHECK_ONLY" -eq 1 ]]; then
	echo "check passed."
else
	for sm in "${ALL_DIRS[@]}"; do
		if is_intree "$sm"; then
			modified=$(git -C "$REPO_ROOT" diff --name-only -- "third_party/$sm" | wc -l | tr -d ' ')
			echo "$sm: $modified file(s) modified (review with 'git -C \"$REPO_ROOT\" diff -- third_party/$sm')"
		else
			modified=$(git -C "$THIRD_PARTY/$sm" diff --name-only | wc -l | tr -d ' ')
			echo "$sm: $modified file(s) modified (review with 'git -C third_party/$sm diff')"
		fi
	done
fi
