#!/usr/bin/env python3
"""Generate the sqllogic test that validates system-table-compatibility.md.

The docs page classifies every pg_catalog / information_schema relation as
supported (green) or stubbed for compatibility (yellow). Nothing used to check
those markers, so they drifted: relations documented as empty stubs had been
returning real rows for a long time.

The generated test pins them. A green relation must return at least one row
against the fixture below; a yellow one only has to be queryable, because the
suite shares a database and another file's DDL can legitimately put rows in a
stub.

Usage:
  python3 scripts/generate_system_table_claims.py [--check]
"""

import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
DOCS = (
    REPO.parent
    / "serenedb-site/docusaurus/docs/compatibility/system-table-compatibility.md"
)
TEST = (
    REPO / "tests/sqllogic/sdb/pg/site_docs/compatibility/system_table_claims.test"
)

SECTIONS = {
    "## System Tables": ("sys_tables", "pg_catalog"),
    "## System Views": ("sys_views", "pg_catalog"),
    "## Information Schema": ("sys_infoschema", "information_schema"),
}

# Green relations whose content cannot be produced by a self-contained fixture.
EXEMPT = {
    # CREATE SERVER validates connectivity, so populating this one needs a
    # reachable remote database.
    "pg_foreign_server",
}

FIXTURE = """statement ok
DROP SCHEMA IF EXISTS stc_s CASCADE

statement ok
DROP VIEW IF EXISTS stc_v

statement ok
DROP TABLE IF EXISTS stc_child

statement ok
DROP TABLE IF EXISTS stc_parent

statement ok
DROP TABLE IF EXISTS stc_audit

statement ok
DROP TYPE IF EXISTS stc_mood

statement ok
DROP SEQUENCE IF EXISTS stc_seq

statement ok
DROP ROLE IF EXISTS stc_member

statement ok
DROP ROLE IF EXISTS stc_role

statement ok
CREATE SCHEMA stc_s

statement ok
CREATE TYPE stc_mood AS ENUM ('ok', 'bad')

statement ok
CREATE TABLE stc_parent (id INT PRIMARY KEY, name TEXT NOT NULL UNIQUE)

statement ok
CREATE TABLE stc_child (
  id INT PRIMARY KEY,
  pid INT REFERENCES stc_parent(id),
  amt NUMERIC CHECK (amt >= 0),
  note TEXT DEFAULT 'x',
  mood stc_mood)

statement ok
CREATE INDEX stc_idx ON stc_child (amt)

statement ok
CREATE VIEW stc_v AS SELECT id, amt FROM stc_child

statement ok
CREATE SEQUENCE stc_seq START 5

statement ok
CREATE TABLE stc_audit (k TEXT, v INT)

statement ok
CREATE TRIGGER stc_trg AFTER DELETE ON stc_child FOR EACH ROW
  INSERT INTO stc_audit VALUES ('d', OLD.id)

statement ok
CREATE MACRO stc_macro(a) AS a + 1

statement ok
COMMENT ON TABLE stc_parent IS 'fixture parent'

statement ok
COMMENT ON COLUMN stc_parent.name IS 'fixture column'

statement ok
CREATE ROLE stc_role

statement ok
CREATE ROLE stc_member

statement ok
GRANT stc_role TO stc_member

statement ok
GRANT SELECT ON stc_parent TO stc_role

statement ok
INSERT INTO stc_parent VALUES (1, 'a')

statement ok
INSERT INTO stc_child VALUES (1, 1, 5, 'n', 'ok')
"""

TEARDOWN = """statement ok
DROP SCHEMA IF EXISTS stc_s CASCADE

statement ok
DROP VIEW IF EXISTS stc_v

statement ok
DROP TABLE IF EXISTS stc_child

statement ok
DROP TABLE IF EXISTS stc_parent

statement ok
DROP TABLE IF EXISTS stc_audit

statement ok
DROP TYPE IF EXISTS stc_mood

statement ok
DROP SEQUENCE IF EXISTS stc_seq

statement ok
DROP ROLE IF EXISTS stc_member

statement ok
DROP ROLE IF EXISTS stc_role
"""


def parse(path):
    section = None
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        for heading, value in SECTIONS.items():
            if line.startswith(heading):
                section = value
        match = re.match(r"\|\s*([a-z_][a-z_0-9]*)\s*\|\s*(🟢|🟡|🔴)\s*\|", line)
        if match and section:
            rows.append((section[0], section[1], match.group(1), match.group(2)))
    return rows


def render(rows):
    out = [
        "# Auto-generated by scripts/generate_system_table_claims.py -- do not edit.",
        "# Claims made by docs/compatibility/system-table-compatibility.md.",
        "#",
        "# A relation documented as supported must return rows against the fixture",
        "# below; one documented as a compatibility stub only has to be queryable,",
        "# since the suite shares a database and another file's DDL may legitimately",
        "# put rows in a stub.",
        "",
        "control substitution on",
        "",
        FIXTURE,
    ]
    for section, schema, name, mark in rows:
        out.append(f"# {section}: {name} ({mark})")
        if mark == "🟢" and name not in EXEMPT:
            out.append("query")
            out.append(f'SELECT count(*) > 0 AS populated FROM {schema}."{name}";')
            out.append("----")
            out.append("populated")
            out.append("t")
        else:
            out.append("statement ok")
            out.append(f'SELECT * FROM {schema}."{name}" LIMIT 0;')
        out.append("")
    out.append(TEARDOWN)
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if not DOCS.exists():
        # The docs page lives in the sibling site repo, which is not always
        # checked out; a hook must not fail because of that.
        print(f"skipped: docs page not found at {DOCS}")
        return 0

    rows = parse(DOCS)
    if not rows:
        print("no claim rows parsed", file=sys.stderr)
        return 1
    rendered = render(rows)

    if args.check:
        current = TEST.read_text(encoding="utf-8") if TEST.exists() else ""
        if current != rendered:
            print(
                f"{TEST} is stale; rerun scripts/generate_system_table_claims.py",
                file=sys.stderr,
            )
            return 1
        print(f"up to date ({len(rows)} claims)")
        return 0

    TEST.write_text(rendered, encoding="utf-8")
    green = sum(1 for r in rows if r[3] == "🟢")
    print(f"wrote {TEST} ({len(rows)} claims, {green} asserted non-empty)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
