import os
import re

import psycopg

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))))
CATALOG_DIR = os.path.join(REPO_ROOT, 'server', 'pg', 'catalog')

SUPERUSER_ONLY_SQL = """
NOT EXISTS (SELECT FROM aclexplode(coalesce(c.relacl,
                                            acldefault('r', c.relowner)))
            WHERE grantee = 0 AND privilege_type = 'SELECT')
AND NOT EXISTS (SELECT FROM pg_attribute a, aclexplode(a.attacl) x
                WHERE a.attrelid = c.oid AND x.grantee = 0
                  AND x.privilege_type = 'SELECT')
"""


def cpp_str(value):
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def cpp_char(value):
    return "'\\\\'" if value == '\\' else f"'{value}'"


def cpp_bool(value):
    return 'true' if value else 'false'


def camel(name):
    return ''.join(
        re.sub(r'(?<=\d)([a-z])', lambda m: m.group(1).upper(),
               part[:1].upper() + part[1:])
        for part in re.split(r'_+', name) if part)


class Generator:
    def __init__(self, pg, pg_src):
        host, port = pg.rsplit(':', 1)
        self.conn = psycopg.connect(host=host, port=int(port),
                                    user='postgres', dbname='postgres',
                                    autocommit=True)
        version = self.query('SELECT version()')[0][0]
        self.version = version.split(' on ')[0]
        self.pg_src = pg_src

    def query(self, sql, params=None):
        return self.conn.execute(sql, params).fetchall()

    def source(self, relpath):
        return os.path.join(self.pg_src, relpath)

    def write(self, relpath, lines):
        path = os.path.join(CATALOG_DIR, relpath)
        with open(path, 'w') as out:
            out.write(f'// Generated by scripts/generate_pg_catalog.py from '
                      f'{self.version}. Do not edit.\n')
            out.write('// clang-format off\n')
            out.writelines(line + '\n' for line in lines)
            out.write('// clang-format on\n')
        print(f'wrote {os.path.relpath(path, REPO_ROOT)}')
