import os
import re

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))))
CATALOG_DIR = os.path.join(REPO_ROOT, 'server', 'pg', 'catalog')
GENERATED_DIR = os.path.join(CATALOG_DIR, 'generated')

SUPERUSER_ONLY_SQL = """
NOT EXISTS (SELECT FROM aclexplode(coalesce(c.relacl,
                                            acldefault('r', c.relowner)))
            WHERE grantee = 0 AND privilege_type = 'SELECT')
AND NOT EXISTS (SELECT FROM pg_attribute a, aclexplode(a.attacl) x
                WHERE a.attrelid = c.oid AND x.grantee = 0
                  AND x.privilege_type = 'SELECT')
"""


def cpp_str(value):
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def cpp_char(value):
    return "'\\\\'" if value == '\\' else f"'{value}'"


def cpp_bool(value):
    return 'true' if value else 'false'


def camel(name):
    return ''.join(
        re.sub(r'(?<=\d)([a-z])', lambda m: m.group(1).upper(),
               part[:1].upper() + part[1:])
        for part in re.split(r'_+', name) if part)


def generated(source, lines):
    return (f'// Generated by scripts/generate_pg_catalog.py from {source}. '
            f'Do not edit.\n// clang-format off\n' +
            ''.join(line + '\n' for line in lines) + '// clang-format on\n')


def write(path, text):
    with open(path, 'w') as out:
        out.write(text)
    print(f'wrote {os.path.relpath(path, REPO_ROOT)}')


class Generator:
    def __init__(self, pg, pg_src):
        import psycopg

        host, port = pg.rsplit(':', 1)
        self.conn = psycopg.connect(host=host, port=int(port),
                                    user='postgres', dbname='postgres',
                                    autocommit=True)
        version = self.query('SELECT version()')[0][0]
        self.version = version.split(' on ')[0]
        self.pg_src = pg_src

    def query(self, sql, params=None):
        return self.conn.execute(sql, params).fetchall()

    def source(self, relpath):
        return os.path.join(self.pg_src, relpath)

    def write(self, name, lines):
        write(os.path.join(GENERATED_DIR, name), generated(self.version, lines))
