# TODO(mbkkt) maybe compiler-rt, libc, etc?
set(LLVM_ENABLE_RUNTIMES "libunwind;libcxxabi;libcxx" CACHE STRING "" FORCE)
set(LLVM_INCLUDE_DOCS OFF)
set(LLVM_INCLUDE_TESTS OFF)
set(LLVM_ENABLE_SPHINX OFF)
set(LLVM_BUILD_32_BITS OFF)
# set(LLVM_ENABLE_LLD ON)
# set(LLVM_ENABLE_LTO "thin" CACHE STRING "" FORCE)
# set(LLVM_ENABLE_ASSERTIONS ON)
# set(LLVM_ENABLE_EXPENSIVE_CHECKS ON)
set(LLVM_UBSAN_FLAGS
    "-fsanitize=undefined -fno-sanitize=vptr,function -fno-sanitize-recover=all"
    CACHE STRING
    ""
    FORCE
)
set(LLVM_USE_SANITIZER "${SDB_SANITIZE}" CACHE STRING "" FORCE)
set(LLVM_OPTIMIZE_SANITIZED_BUILDS ON)
set(LLVM_ENABLE_EH ON)
set(LLVM_ENABLE_RTTI ON)

set(LIBUNWIND_ENABLE_CET OFF)
set(LIBUNWIND_ENABLE_ASSERTIONS OFF)
set(LIBUNWIND_ENABLE_PEDANTIC OFF)
set(LIBUNWIND_ENABLE_WERROR OFF)
set(LIBUNWIND_ENABLE_SHARED OFF)
set(LIBUNWIND_ENABLE_STATIC ON)
set(LIBUNWIND_ENABLE_CROSS_UNWINDING OFF)
set(LIBUNWIND_ENABLE_ARM_WMMX OFF)
set(LIBUNWIND_ENABLE_THREADS ON)
set(LIBUNWIND_WEAK_PTHREAD_LIB OFF)
set(LIBUNWIND_USE_COMPILER_RT ON)
set(LIBUNWIND_IS_BAREMETAL OFF)
set(LIBUNWIND_USE_FRAME_HEADER_CACHE OFF)
set(LIBUNWIND_REMEMBER_HEAP_ALLOC OFF)
set(LIBUNWIND_INSTALL_HEADERS OFF)
set(LIBUNWIND_ENABLE_FRAME_APIS OFF)
set(LIBUNWIND_INSTALL_LIBRARY OFF)
set(LIBUNWIND_HIDE_SYMBOLS ON)

set(LIBCXXABI_ENABLE_EXCEPTIONS ON)
set(LIBCXXABI_ENABLE_ASSERTIONS OFF)
set(LIBCXXABI_ENABLE_PEDANTIC OFF)
set(LIBCXXABI_ENABLE_WERROR OFF)
set(LIBCXXABI_ENABLE_STATIC_UNWINDER ON)
if(LLVM_USE_SANITIZER MATCHES "(Thread)|(Memory(WithOrigins)?)")
    set(LIBCXXABI_USE_LLVM_UNWINDER OFF)
    set(LIBCXXABI_USE_COMPILER_RT OFF)
else()
    set(LIBCXXABI_USE_LLVM_UNWINDER ON)
    set(LIBCXXABI_USE_COMPILER_RT ON)
endif()
set(LIBCXXABI_ENABLE_THREADS ON)
# TODO set(LIBCXXABI_HAS_PTHREAD_API OFF)
# TODO set(LIBCXXABI_HAS_WIN32_THREAD_API OFF)
# TODO set(LIBCXXABI_HAS_EXTERNAL_THREAD_API OFF)
set(LIBCXXABI_ENABLE_FORGIVING_DYNAMIC_CAST OFF)
set(LIBCXXABI_ENABLE_NEW_DELETE_DEFINITIONS ON)
set(LIBCXXABI_INSTALL_HEADERS OFF)
set(LIBCXXABI_INSTALL_LIBRARY OFF)
set(LIBCXXABI_ENABLE_SHARED OFF)
set(LIBCXXABI_ENABLE_STATIC ON)
set(LIBCXXABI_BAREMETAL OFF)
set(LIBCXXABI_SILENT_TERMINATE OFF)
set(LIBCXXABI_NON_DEMANGLING_TERMINATE OFF)
set(LIBCXXABI_HERMETIC_STATIC_LIBRARY ON)

set(LIBCXX_ENABLE_ASSERTIONS OFF)
set(LIBCXX_ENABLE_SHARED OFF)
set(LIBCXX_ENABLE_STATIC ON)
set(LIBCXX_ENABLE_FILESYSTEM ON)
# TODO LIBCXX_HARDENING_MODE
# TODO LIBCXX_ASSERTION_HANDLER_FILE
set(LIBCXX_ENABLE_RANDOM_DEVICE ON)
set(LIBCXX_ENABLE_LOCALIZATION ON)
set(LIBCXX_ENABLE_UNICODE ON)
set(LIBCXX_ENABLE_WIDE_CHARACTERS ON)
set(LIBCXX_ENABLE_TIME_ZONE_DATABASE ON)
set(LIBCXX_ENABLE_VENDOR_AVAILABILITY_ANNOTATIONS OFF)
set(LIBCXX_ENABLE_CLANG_TIDY OFF)
set(LIBCXX_INCLUDE_BENCHMARKS OFF)
set(LIBCXX_INSTALL_HEADERS OFF)
set(LIBCXX_INSTALL_LIBRARY OFF)
set(LIBCXX_INSTALL_MODULES OFF)
set(LIBCXX_ABI_UNSTABLE ON)
# TODO set(LIBCXX_ABI_FORCE_ITANIUM OFF)
# TODO set(LIBCXX_ABI_FORCE_MICROSOFT OFF)
# TODO LIBCXX_TYPEINFO_COMPARISON_IMPLEMENTATION
set(LIBCXX_USE_COMPILER_RT ON)
# TODO LIBCXX_CXX_ABI
set(LIBCXX_ENABLE_STATIC_ABI_LIBRARY ON)
set(LIBCXX_ENABLE_NEW_DELETE_DEFINITIONS OFF)
set(LIBCXX_ENABLE_EXCEPTIONS ON)
set(LIBCXX_ENABLE_RTTI ON)
set(LIBCXX_ENABLE_THREADS ON)
set(LIBCXX_ENABLE_MONOTONIC_CLOCK ON)
if("${DISTRIB_NAME}" MATCHES "Alpine")
    set(LIBCXX_HAS_MUSL_LIBC ON)
else()
    set(LIBCXX_HAS_MUSL_LIBC OFF)
endif()
# TODO set(LIBCXX_HAS_PTHREAD_API OFF)
# TODO set(LIBCXX_HAS_WIN32_THREAD_API OFF)
# TODO set(LIBCXX_HAS_EXTERNAL_THREAD_API OFF)
set(LIBCXX_PSTL_CPU_BACKEND "serial" CACHE STRING "" FORCE)
set(LIBCXX_ENABLE_PEDANTIC OFF)
set(LIBCXX_ENABLE_WERROR OFF)
set(LIBCXX_GENERATE_COVERAGE OFF)
set(LIBCXX_HERMETIC_STATIC_LIBRARY ON)

include(UpdateModule)

sdb_update_module(${GIT_EXECUTABLE} "llvm-project" ${CMAKE_SOURCE_DIR}/third_party "LICENSE.TXT")

add_subdirectory(third_party/llvm-project/runtimes EXCLUDE_FROM_ALL)

if(${SDB_GTEST})
    # Need this for building velox fuzzer that is used for tests.
    # TODO(Dronplane) propose a fix without deprecated stuff
    target_compile_definitions(
        cxx_static
        PUBLIC _LIBCPP_ENABLE_CXX26_REMOVED_WSTRING_CONVERT
    )
    target_compile_definitions(
        cxx_static
        PUBLIC _LIBCPP_ENABLE_CXX26_REMOVED_CODECVT
    )
endif()
