#!/bin/bash

WORKDIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)/..
cd $WORKDIR

CMAKELIST="CMakeLists.txt"
AV="set(SERENEDB_VERSION"
APR="set(SERENEDB_PACKAGE_REVISION"

SEDFIX='s/.*"\([0-9a-zA-Z]*\)".*$/\1/'

export SERENEDB_VERSION_MAJOR=$(grep "$AV""_MAJOR" $CMAKELIST | sed -e $SEDFIX)
export SERENEDB_VERSION_MINOR=$(grep "$AV""_MINOR" $CMAKELIST | sed -e $SEDFIX)

export SERENEDB_SNIPPETS="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR"
export SERENEDB_PACKAGES="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR"

export SERENEDB_VERSION_PATCH=$(grep "$AV""_PATCH" $CMAKELIST | grep -v unset | sed -e $SEDFIX)
export SERENEDB_VERSION_RELEASE_TYPE=$(grep "$AV""_RELEASE_TYPE" $CMAKELIST | grep -v unset | sed -e $SEDFIX)
export SERENEDB_VERSION_RELEASE_NUMBER=$(grep "$AV""_RELEASE_NUMBER" $CMAKELIST | grep -v unset | sed -e $SEDFIX)

# stable release
if [[ "$SERENEDB_VERSION_RELEASE_TYPE" = "" ]]; then
  export SERENEDB_VERSION="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH"

  export SERENEDB_DARWIN_UPSTREAM="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH"
  export SERENEDB_DARWIN_REVISION=""

  export SERENEDB_DEBIAN_UPSTREAM="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH"
  export SERENEDB_DEBIAN_REVISION="1"

  export SERENEDB_TGZ_UPSTREAM="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH"

  export SERENEDB_RPM_UPSTREAM="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH"
  export SERENEDB_RPM_REVISION="1.0"

  export SERENEDB_REPO="serenedb""$SERENEDB_VERSION_MAJOR""$SERENEDB_VERSION_MINOR"

  export DOCKER_TAG="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH"

# devel or nightly
elif [[ "$SERENEDB_VERSION_RELEASE_TYPE" = "devel" ]] || [[ "$SERENEDB_VERSION_RELEASE_TYPE" = "nightly" ]]; then
  export SERENEDB_VERSION="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH-$SERENEDB_VERSION_RELEASE_TYPE"

  export DOCKER_TAG="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH-$SERENEDB_VERSION_RELEASE_TYPE"

  export SERENEDB_DARWIN_UPSTREAM="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH.$SERENEDB_VERSION_RELEASE_TYPE"
  export SERENEDB_DARWIN_REVISION="$SERENEDB_VERSION_RELEASE_TYPE"

  export SERENEDB_DEBIAN_UPSTREAM="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH~~$SERENEDB_VERSION_RELEASE_TYPE"
  export SERENEDB_DEBIAN_REVISION="1"

  export SERENEDB_TGZ_UPSTREAM="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH-$SERENEDB_VERSION_RELEASE_TYPE"

  if [[ "$SERENEDB_VERSION_RELEASE_TYPE" = "devel" ]]; then
    export SERENEDB_RPM_UPSTREAM="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH"
    export SERENEDB_RPM_REVISION="0.1"
    export SERENEDB_REPO=nightly
  elif [[ "$SERENEDB_VERSION_RELEASE_TYPE" = "nightly" ]]; then
    export SERENEDB_RPM_UPSTREAM="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH"
    export SERENEDB_RPM_REVISION="0.2"
    export SERENEDB_REPO=nightly
  fi

# unstable release, devel or nightly
elif [[ "$SERENEDB_VERSION_RELEASE_TYPE" = "alpha" ]] ||
  [[ "$SERENEDB_VERSION_RELEASE_TYPE" = "beta" ]] ||
  [[ "$SERENEDB_VERSION_RELEASE_TYPE" = "milestone" ]] ||
  [[ "$SERENEDB_VERSION_RELEASE_TYPE" = "preview" ]] ||
  [[ "$SERENEDB_VERSION_RELEASE_TYPE" = "rc" ]]; then
  if [[ "$SERENEDB_VERSION_RELEASE_NUMBER" = "" ]]; then
    echo "ERROR: missing SERENEDB_VERSION_RELEASE_NUMBER for type $SERENEDB_VERSION_RELEASE_TYPE"
    return
  fi

  if [[ "$SERENEDB_VERSION_RELEASE_TYPE" = "alpha" ]]; then
    N=100
  elif [[ "$SERENEDB_VERSION_RELEASE_TYPE" = "beta" ]]; then
    N=200
  elif [[ "$SERENEDB_VERSION_RELEASE_TYPE" = "milestone" ]]; then
    N=300
  elif [[ "$SERENEDB_VERSION_RELEASE_TYPE" = "preview" ]]; then
    N=400
  elif [[ "$SERENEDB_VERSION_RELEASE_TYPE" = "rc" ]]; then
    N=500
  fi

  export SERENEDB_VERSION="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH-$SERENEDB_VERSION_RELEASE_TYPE.$SERENEDB_VERSION_RELEASE_NUMBER"

  export SERENEDB_DEBIAN_UPSTREAM="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH~$SERENEDB_VERSION_RELEASE_TYPE.$SERENEDB_VERSION_RELEASE_NUMBER"
  export SERENEDB_DEBIAN_REVISION="1"

  export SERENEDB_RPM_UPSTREAM="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH"
  export SERENEDB_RPM_REVISION="0."$(expr $N + $SERENEDB_VERSION_RELEASE_NUMBER)".$SERENEDB_VERSION_RELEASE_TYPE$SERENEDB_VERSION_RELEASE_NUMBER"

  export SERENEDB_DARWIN_UPSTREAM="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH-$SERENEDB_VERSION_RELEASE_TYPE.$SERENEDB_VERSION_RELEASE_NUMBER"
  export SERENEDB_DARWIN_REVISION=""

  export SERENEDB_TGZ_UPSTREAM="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH-$SERENEDB_VERSION_RELEASE_TYPE.$SERENEDB_VERSION_RELEASE_NUMBER"

  export SERENEDB_REPO="serenedb""$SERENEDB_VERSION_MAJOR""$SERENEDB_VERSION_MINOR-$SERENEDB_VERSION_RELEASE_TYPE.$SERENEDB_VERSION_RELEASE_NUMBER"

  export DOCKER_TAG="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH-$SERENEDB_VERSION_RELEASE_TYPE.$SERENEDB_VERSION_RELEASE_NUMBER"

# hot-fix
else
  if [[ "$SERENEDB_VERSION_RELEASE_NUMBER" != "" ]]; then
    echo "ERROR: SERENEDB_VERSION_RELEASE_NUMBER ($SERENEDB_VERSION_RELEASE_NUMBER) must be empty for type $SERENEDB_VERSION_RELEASE_TYPE"
    return
  fi

  export SERENEDB_VERSION="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH-$SERENEDB_VERSION_RELEASE_TYPE"

  export SERENEDB_DEBIAN_UPSTREAM="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH.$SERENEDB_VERSION_RELEASE_TYPE"
  export SERENEDB_DEBIAN_REVISION="1"

  export SERENEDB_RPM_UPSTREAM="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH"
  export SERENEDB_RPM_REVISION="1.$SERENEDB_VERSION_RELEASE_TYPE"

  export SERENEDB_DARWIN_UPSTREAM="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH.$SERENEDB_VERSION_RELEASE_TYPE"
  export SERENEDB_DARWIN_REVISION=""

  export SERENEDB_TGZ_UPSTREAM="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH-$SERENEDB_VERSION_RELEASE_TYPE"

  export SERENEDB_REPO="serenedb""$SERENEDB_VERSION_MAJOR""$SERENEDB_VERSION_MINOR"

  export DOCKER_TAG="$SERENEDB_VERSION_MAJOR.$SERENEDB_VERSION_MINOR.$SERENEDB_VERSION_PATCH.$SERENEDB_VERSION_RELEASE_TYPE"
fi

if [[ -n "${DOCKER_DISTRO:-}" ]] && [[ "${DOCKER_DISTRO:-}" != "alpine" ]]; then
  export DOCKER_TAG="${DOCKER_TAG}-${DOCKER_DISTRO}"
fi

echo '------------------------------------------------------------------------------'
echo "SERENEDB_VERSION:                  $SERENEDB_VERSION"
echo
echo "SERENEDB_VERSION_MAJOR:            $SERENEDB_VERSION_MAJOR"
echo "SERENEDB_VERSION_MINOR:            $SERENEDB_VERSION_MINOR"
echo "SERENEDB_VERSION_PATCH:            $SERENEDB_VERSION_PATCH"
echo "SERENEDB_VERSION_RELEASE_TYPE:     $SERENEDB_VERSION_RELEASE_TYPE"
echo "SERENEDB_VERSION_RELEASE_NUMBER:   $SERENEDB_VERSION_RELEASE_NUMBER"
echo
echo "SERENEDB_DARWIN_UPSTREAM/REVISION: $SERENEDB_DARWIN_UPSTREAM / $SERENEDB_DARWIN_REVISION"
echo "SERENEDB_DEBIAN_UPSTREAM/REVISION: $SERENEDB_DEBIAN_UPSTREAM / $SERENEDB_DEBIAN_REVISION"
echo "SERENEDB_PACKAGES:                 $SERENEDB_PACKAGES"
echo "SERENEDB_REPO:                     $SERENEDB_REPO"
echo "SERENEDB_RPM_UPSTREAM/REVISION:    $SERENEDB_RPM_UPSTREAM / $SERENEDB_RPM_REVISION"
echo "SERENEDB_SNIPPETS:                 $SERENEDB_SNIPPETS"
echo "SERENEDB_TGZ_UPSTREAM:             $SERENEDB_TGZ_UPSTREAM"
echo "DOCKER_TAG:                        $DOCKER_TAG"
echo '------------------------------------------------------------------------------'
echo
