////////////////////////////////////////////////////////////////////////////////
/// DISCLAIMER
///
/// Copyright 2014-2023 ArangoDB GmbH, Cologne, Germany
/// Copyright 2004-2014 triAGENS GmbH, Cologne, Germany
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///
///     http://www.apache.org/licenses/LICENSE-2.0
///
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
///
/// Copyright holder is ArangoDB GmbH, Cologne, Germany
////////////////////////////////////////////////////////////////////////////////

#pragma once

#include <s2/s2latlng.h>
#include <s2/s2region_coverer.h>

#include <cmath>
#include <cstddef>
#include <limits>
#include <string>

#include "basics/assert.h"
#include "geo/shape_container.h"

namespace vpack {

class Builder;
class Slice;

}  // namespace vpack
namespace sdb {
namespace geo {

// assume up to 8x machine epsilon in precision errors for radian calculations
inline constexpr double kRadEps = 8 * std::numeric_limits<double>::epsilon();
inline constexpr double kMaxRadiansBetweenPoints = M_PI + kRadEps;
// Equatorial radius of earth.
// Source: http://nssdc.gsfc.nasa.gov/planetary/factsheet/earthfact.html
// Equatorial radius
// inline constexpr double kEarthRadiusInMeters = 6'378'137.0;
// Volumetric mean radius
inline constexpr double kEarthRadiusInMeters = 6'371'000.0;
inline constexpr double kMaxDistanceBetweenPoints =
  kMaxRadiansBetweenPoints * kEarthRadiusInMeters;

constexpr double MetersToRadians(double distance_in_meters) noexcept {
  return std::clamp(distance_in_meters / kEarthRadiusInMeters, 0.0, M_PI);
}

enum class FilterType {
  // no filter, only useful on a near query
  None,
  // Select documents with geospatial data that are located entirely
  // within a shape.
  // When determining inclusion, we consider the border of a shape to
  // be part of the shape,
  // subject to the precision of floating point numbers.
  Contains,
  // Select documents whose geospatial data intersects with a
  // specified GeoJSON object.
  Intersects,
};

/// contains parameters for s2 region coverer
struct RegionCoverParams {
  RegionCoverParams();
  RegionCoverParams(int m_c, int w_l, int b_l)
    : max_num_cover_cells(m_c),
      worst_indexed_level(w_l),
      best_indexed_level(b_l) {
    SDB_ASSERT(m_c > 0 && w_l > 0 && b_l > 0 && w_l < b_l);
  }

  /// read the options from a vpack slice
  void fromVPack(vpack::Slice slice);

  /// add the options to an opened vpack builder
  void toVPack(vpack::Builder& builder) const;

  S2RegionCoverer::Options regionCovererOpts() const;

  static constexpr int kMaxNumCoverCellsDefault = 8;
  // Should indicate the max number of cells generated by the S2RegionCoverer
  // is treated as a soft limit, only other params are fixed
  int max_num_cover_cells;
  // Least detailed level used in coverings. Value between [0, 30]
  int worst_indexed_level;
  // Most detailed level used. Value between [0, 30]
  int best_indexed_level;
};

struct QueryParams {
  QueryParams() noexcept
    : origin(S2LatLng::Invalid()),
      cover(kQueryMaxCoverCells, kQueryWorstLevel, kQueryBestLevel) {}

  /// This query only needs to support points no polygons etc
  // bool onlyPoints = false;

  // ============== Near Query Params =============

  /// Min distance from centroid a result has to be
  double min_distance = 0.0;
  /// is minimum an exclusive bound
  bool min_inclusive = false;

  /// entire earth (halfaround in each direction),
  /// may not be larger than half earth circumference or larger
  /// than the bounding cap of the filter region (see _filter)
  double max_distance = kMaxDistanceBetweenPoints;
  bool max_inclusive = false;

  /// Some condition on min and max distances are given, this starts out
  /// as false and must be set whenever the values minDistance, minInclusive
  /// maxDistance and maxInclusive are intended to take effect.
  bool distance_restricted = false;
  /// results need to be sorted by distance to centroid
  bool sorted = false;
  /// Default order is from closest to farthest
  bool ascending = true;

  /// Centroid from which to sort by distance
  S2LatLng origin;

  // =================== Hints ===================

  /// Index only contains points; no need to consider larger polygons
  bool points_only = false;
  /// If non-zero, we will use a LIMIT clause later with this value
  size_t limit = 0;

  // ============= Filtered Params ===============

  FilterType filter_type = FilterType::None;
  ShapeContainer filter_shape;

  // parameters to calculate the cover for index
  // lookup intervals
  RegionCoverParams cover;

 public:
  /// minimum distance
  double minDistanceRad() const noexcept;

  /// depending on @{filter} and @{region} uses maxDistance or
  /// maxDistance / kEarthRadius or a bounding circle around
  /// the area in region
  double maxDistanceRad() const noexcept;

  /// some defaults for queries
  static constexpr int kQueryMaxCoverCells = 20;
  static constexpr int kQueryWorstLevel = 4;
  static constexpr int kQueryBestLevel = 23;  // about 1m

  std::string toString() const;
};

}  // namespace geo
}  // namespace sdb
