name: auto | pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 1
        submodules: false
        clean: false
    - uses: actions/setup-python@v6
    # No floating v3 tag -- only specific versions published
    - uses: pre-commit/action@v3.0.1
