#!/usr/bin/env bash
# Generates the filtered-top-k A-vs-B report from live measurements.
#
#   A = WAND + filter        (sdb_disable_top_k_optimization=false) -- the new path:
#       the column filter is pushed into the WAND/top-k collector and the filter
#       column is read in batches (process_block -> AddDocs -> MatchesBatch/RangeScan).
#   B = streaming + TopN     (sdb_disable_top_k_optimization=true)  -- the previous path:
#       the iResearch scan streams scored matches (filter pushed down) and a TOP_N
#       operator above takes the k.
#
# Usage: scripts/perf/gen_filtered_topk_report.sh <port> [out.md] [runs]
#   - <port>   : a serened with the study dataset loaded (scripts/perf/study_setup.sql).
#   - [out.md] : output path (default scripts/perf/filtered_topk_report.md).
#   - [runs]   : warm runs per cell, min/median reported (default 9).
# Pin the server to idle cores for stable absolute numbers, e.g.
#   taskset -c 8-15,24-31 ./build_bench/bin/serened <datadir> --server_endpoints=pgsql+tcp://0.0.0.0:<port>
set -euo pipefail

PORT="${1:?usage: gen_filtered_topk_report.sh <port> [out.md] [runs]}"
OUT="${2:-scripts/perf/filtered_topk_report.md}"
N="${3:-9}"
PSQL="psql -h 127.0.0.1 -p $PORT -U postgres -d postgres -tA"

$PSQL -c "SELECT 1 FROM dt LIMIT 1" >/dev/null 2>&1 || {
	echo "error: index 'dt' not reachable on port $PORT -- load scripts/perf/study_setup.sql first" >&2
	exit 1
}

# --- measurement helpers --------------------------------------------------
# runq <setting> <query>  ->  "min median" (ms) over N warm runs
runq() {
	local setting="$1" q="$2" body="" i
	for ((i = 0; i < N; i++)); do body="$body
$q"; done
	$PSQL <<EOF 2>&1 | grep -oE "Time: [0-9.]+ ms" | grep -oE "[0-9.]+" | sort -g |
SET sdb_disable_top_k_optimization=$setting;
\timing on
$body
EOF
		awk '{a[NR]=$1} END{printf "%.2f %.2f", a[1], a[int((NR+1)/2)]}'
}

topk() { # term filter limit -> a discarded SELECT
	local w="body @@ ts_phrase('$1')"
	[ -n "$2" ] && w="$w AND $2"
	echo "SELECT id FROM dt WHERE $w ORDER BY BM25(dt.tableoid) DESC LIMIT $3 \\g /dev/null"
}

cnt() { # filter -> rows matching fox AND filter
	local w="body @@ ts_phrase('fox')"
	[ -n "$1" ] && w="$w AND $1"
	$PSQL -c "SELECT count(*) FROM dt WHERE $w;"
}

RATIOS="$(mktemp)" # "ratio<TAB>label" per scenario, for the summary
row() {            # label term filter limit  -> append a markdown table row to $SEC
	local label="$1" a b amed bmed ratio
	a=($(runq false "$(topk "$2" "$3" "$4")"))
	b=($(runq true "$(topk "$2" "$3" "$4")"))
	amed=${a[1]}
	bmed=${b[1]}
	ratio=$(awk "BEGIN{if($amed>0)printf \"%.1f\",$bmed/$amed;else print \"-\"}")
	printf "| %s | %s | %s | %s | %s | **%sx** |\n" \
		"$label" "${a[0]}" "$amed" "${b[0]}" "$bmed" "$ratio" >>"$SEC"
	printf "%s\t%s\n" "$ratio" "$label" >>"$RATIOS"
}

thead() { printf "| %s | A min | A med | B min | B med | B/A med |\n|---|--:|--:|--:|--:|--:|\n" "$1" >>"$SEC"; }

# --- gather live dataset facts --------------------------------------------
FOX=$(cnt "")
LO=$(cnt "tf_col<=3")
MID=$(cnt "tf_col>=9 AND tf_col<=11")
HI=$(cnt "tf_col>=18")
R15=$(cnt "r<15")
G5=$(cnt "g<=5")
TOTAL=$($PSQL -c "SELECT count(*) FROM d;")
ZEBRA=$($PSQL -c "SELECT count(*) FROM dt WHERE body @@ ts_phrase('zebra');")
pct() { awk "BEGIN{printf \"%.0f\", 100.0*$1/$2}"; }

# =========================================================================
SEC="$(mktemp)"
{
	echo "# Filtered top-k: WAND+filter vs streaming+filter-pushdown+TopN"
	echo
	echo "_Generated by \`scripts/perf/gen_filtered_topk_report.sh\` ($N warm runs, min/median ms; \`B/A\` uses medians)._"
	echo
	echo "## What is compared"
	echo "Both paths run on the **same binary** (\`build_bench\`, Release / \`-O3\` / \`-DNDEBUG\` / \`SDB_DEV=Off\`),"
	echo "selected by the \`sdb_disable_top_k_optimization\` session setting:"
	echo
	echo "- **A = WAND + filter** (\`=false\`) -- the column filter is pushed into the WAND/top-k"
	echo "  collector; the filter column is read in **batches** per score block"
	echo "  (\`process_block\` -> \`AddDocs\` -> \`MatchesBatch\`/\`RangeScan\`), so each bitpacked group is"
	echo "  decoded once, sequentially."
	echo "- **B = streaming + TopN** (\`=true\`) -- the iResearch scan runs the \`@@\` search, applies the"
	echo "  column filter (rg-prune + row-level), streams scored matches, and a \`TOP_N\` operator takes the k."
	echo
	echo "Query template (only \`<term>\`, \`<filter>\`, \`<k>\` vary):"
	echo
	echo '```sql'
	echo "SELECT id FROM dt"
	echo "WHERE body @@ ts_phrase('<term>') [AND <filter>]"
	echo "ORDER BY BM25(dt.tableoid) DESC"
	echo "LIMIT <k>;"
	echo '```'
	echo
	echo "## Dataset (${TOTAL} rows)"
	echo "- \`body\` = \`'fox'\` repeated \`tf\` times in ~70% of docs (${FOX} match \`@@ 'fox'\`), else \`'dog cat bird'\`;"
	echo "  \`'zebra'\` in ~0.1% (${ZEBRA} docs, the rare query term)."
	echo "- \`tf_col = (id%20)+1\` -- the BM25 score driver (1..20)."
	echo "- \`r = hash(id+c)%100\` -- a filter column **statistically independent of score**."
	echo "- \`g = id/5000\` -- a filter column **clustered** in storage order (rg-prune applies)."
	echo "- \`tf_col\`, \`r\`, \`g\` are all \`INCLUDE\`d so the columnstore can read them."
	echo
	echo "## [1] Selectivity sweep -- filter independent of score (term=fox, k=10)"
} >"$OUT"

SEC="$OUT"
thead "filter"
row "unfiltered (100%)" fox "" 10
row "r<90 (~90%)" fox "r<90" 10
row "r<50 (~50%)" fox "r<50" 10
row "r<25 (~25%)" fox "r<25" 10
row "r<10 (~10%)" fox "r<10" 10
row "r<5 (~5%)" fox "r<5" 10
row "r<1 (~1%)" fox "r<1" 10

{
	echo
	echo "Selectivity alone never hurts WAND: A grows gently as it works harder to accumulate k"
	echo "survivors; B is ~flat (it scores all matches regardless of the filter)."
	echo
	echo "## [2] Score-correlation -- all ~$(pct "$R15" "$FOX")% selective (the decisive variable) (term=fox, k=10)"
} >>"$OUT"
thead "filter"
row "tf>=18 (HIGH score, $(pct "$HI" "$FOX")%, corr)" fox "tf_col>=18" 10
row "r<15 (independent, $(pct "$R15" "$FOX")%)" fox "r<15" 10
row "tf 9-11 (MID score, $(pct "$MID" "$FOX")%)" fox "tf_col>=9 AND tf_col<=11" 10
row "tf<=3 (LOW score, $(pct "$LO" "$FOX")%, anti-corr)" fox "tf_col<=3" 10

{
	echo
	echo "This used to be the regression case: when the filter **excludes the top scorers** (mid/low"
	echo "bands), θ stayed low and WAND walked ~all matches doing a **per-doc random read** of the"
	echo "bitpacked filter column. With the batched read, each score block's filter values are decoded"
	echo "in one sequential pass -- so WAND now wins here too, at the same selectivity."
	echo
	echo "## [3] Term frequency (df) (k=10)"
} >>"$OUT"
thead "query"
row "fox (common ${FOX}), unfiltered" fox "" 10
row "zebra (rare ${ZEBRA}), unfiltered" zebra "" 10
row "fox, r<10" fox "r<10" 10
row "zebra, r<10" zebra "r<10" 10

{
	echo
	echo "WAND's win is largest for **broad terms** (B scores them all); for **rare terms** B is already"
	echo "fast so the gap is small."
	echo
	echo "## [4] LIMIT (k) -- fox, r<10"
} >>"$OUT"
thead "k"
row "1" fox "r<10" 1
row "10" fox "r<10" 10
row "100" fox "r<10" 100

{
	echo
	echo "A scales with k (collect more); B is k-independent (scores everything regardless)."
	echo
	echo "## [5] Clustered filter (rg-prune helps streaming)"
} >>"$OUT"
thead "query"
row "fox, g<=5 (clustered ${G5})" fox "g<=5" 10

# --- data-driven conclusion ----------------------------------------------
WORST=$(sort -g "$RATIOS" | head -1)
BEST=$(sort -g "$RATIOS" | tail -1)
wmin=$(echo "$WORST" | cut -f1)
wlbl=$(echo "$WORST" | cut -f2)
bmax=$(echo "$BEST" | cut -f1)
blbl=$(echo "$BEST" | cut -f2)
verdict=$(awk "BEGIN{print ($wmin>=1.0)?\"win\":\"regress\"}")
{
	echo
	echo "rg-prune cuts B sharply, but A still wins."
	echo
	echo "## Conclusion"
	if [ "$verdict" = win ]; then
		echo "**A (WAND+filter) wins every measured scenario.** The narrowest margin is **${wmin}x**"
		echo "(\`${wlbl}\`); the widest is **${bmax}x** (\`${blbl}\`)."
		echo
		echo "The former anti-/mid-correlated regression is gone: the root cause was a **per-doc random"
		echo "read of the bitpacked filter column** (\`FetchRow\`->\`Skip\`->\`fastunpack\`, ~70% of the bad-case"
		echo "profile), not anything fundamental to WAND. Batching the filter read per score block"
		echo "(\`process_block\` -> \`AddDocs\` -> \`MatchesBatch\`/\`RangeScan\`) decodes each bitpacked group once"
		echo "and closed the gap."
	else
		echo "**A regresses in at least one scenario:** worst B/A = **${wmin}x** (\`${wlbl}\`). Investigate."
	fi
	echo
	echo "## Reproduce"
	echo "- \`scripts/perf/study_setup.sql\` -- the controlled dataset."
	echo "- \`scripts/perf/gen_filtered_topk_report.sh <port>\` -- this report (A vs B, $N-run min/median)."
	echo "- Server: \`taskset -c 8-15,24-31 ./build_bench/bin/serened <datadir> --server_endpoints=pgsql+tcp://0.0.0.0:<port>\`"
} >>"$OUT"

rm -f "$RATIOS"
echo "wrote $OUT"
